logging:
  file: FeaturesCacheManager.log
  level:
    org.springframework: DEBUG
    io.pivotal: INFO 
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
    
server:
      port: 8087          
  
spring:
  application:
    name:  Madlib Features Cache loading Application
  
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
   
   
#source database
---
modeldb-datasource:
  jdbc-url: 
  username: 
  password: 
  driverClassName: org.postgresql.Driver
  
---    
pcc:
  locators: 
  port: 1
  username: 
  password: 
  
---    
gemfire:
  locator: 
  port: 1
  username: 
  password: 
  server:
  sport:
 
---
# Redis Standalone
redis:
  clustertype: 
  hostname: 
  port: 6379
  password:
  master:
  servers:
  
  
---
feature-cache:
  featurename: 
  featuresourceschema: 
  loadbatchsize: 500
  featurefunctions:
    - 
  featuresourcetables:

    
#---
 
 
 
# samples 
#redis:
#  clustertype: standlone
#  hostname: 127.0.0.1
#  port: 6379
#  master:
#  servers:

# Redis Sentinel    
#redis:
#  clustertype: ha
#  master: "masternode"
#  servers:
#    - 127.0.0.1:26379
#    - 127.0.0.1:26380