#-----------------------------------------------------------------------------------------------
# Copyright 2019 Sridhar Paladugu

# Permission is hereby granted, free of charge, to any person obtaining a copy of this 
# software and associated documentation files (the "Software"), to deal in the Software 
# without restriction, including without limitation the rights to use, copy, modify, 
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to 
# permit persons to whom the Software is furnished to do so, subject to the following 
# conditions:

# The above copyright notice and this permission notice shall be included in all copies 
# or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
# PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
# FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR 
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
# OTHER DEALINGS IN THE SOFTWARE.
#----------------------------------------------------------------------------------------------
# APP DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: $APP_NAME-madlibfeaturescacheloader
  name: $APP_NAME-madlibfeaturescacheloader
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      run: $APP_NAME-madlibfeaturescacheloader-exposed
  template:
    metadata:
      labels:
        run: $APP_NAME-madlibfeaturescacheloader-exposed
    spec:
      containers:
        - name: $APP_NAME-madlibfeaturescacheloader
          image: $MADLIBFLOW_DOCKER_REG/madlibflow/madlibfeaturescacheloader:$RTSMADLIB_IMG_TAG
          imagePullPolicy: IfNotPresent
          env:
            - name: MADLIBFEATURESCACHE_APP_JSON
              valueFrom:
                configMapKeyRef:
                  name: $APP_NAME-madlibfeaturescacheloader-config
                  key: springjson
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "/docker-entrypoint-initdb.d/init_container.sh \"${MADLIBFEATURESCACHE_APP_JSON}\""]
          ports:
            - containerPort: 8087
              protocol: TCP
      imagePullSecrets:
        - name: regcred

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: $APP_NAME-madlibfeaturescacheloader
  name: $APP_NAME-madlibfeaturescacheloader
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 8087
    targetPort: 8087
  selector:
    run: $APP_NAME-madlibfeaturescacheloader-exposed
