#-----------------------------------------------------------------------------------------------
#   Copyright 2019 Pivotal Software
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#----------------------------------------------------------------------------------------------

# Author: Sridhar Paladugu 
# Email: spaladugu@pivotal.io
# Description: Features Cache manager deployment manifest
# APP DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: $APP_NAME-madlibfeaturescacheloader
  name: $APP_NAME-madlibfeaturescacheloader
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      run: $APP_NAME-madlibfeaturescacheloader-exposed
  template:
    metadata:
      labels:
        run: $APP_NAME-madlibfeaturescacheloader-exposed
    spec:
      containers:
        - name: $APP_NAME-madlibfeaturescacheloader
          image: $MADLIBFLOW_DOCKER_REG/madlibflow/madlibfeaturescacheloader:$RTSMADLIB_IMG_TAG
          imagePullPolicy: IfNotPresent
          env:
            - name: MADLIBFEATURESCACHE_APP_JSON
              valueFrom:
                configMapKeyRef:
                  name: $APP_NAME-madlibfeaturescacheloader-config
                  key: springjson
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "/docker-entrypoint-initdb.d/init_container.sh \"${MADLIBFEATURESCACHE_APP_JSON}\""]
          ports:
            - containerPort: 8087
              protocol: TCP
      imagePullSecrets:
        - name: regcred

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: $APP_NAME-madlibfeaturescacheloader
  name: $APP_NAME-madlibfeaturescacheloader
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 8087
    targetPort: 8087
  selector:
    run: $APP_NAME-madlibfeaturescacheloader-exposed
